image: docker:latest              # The runner will use this base environment (Docker installed)

services:
  - docker:dind                   # Enables Docker-in-Docker (lets CI run docker commands)

variables:
  DOCKER_DRIVER: overlay2         # Storage driver for Docker, keeps it stable in CI

stages:
  - test                          # One stage: "test"

before_script:
  - apk add --no-cache docker-compose   # Install docker-compose inside the runner

test:
  stage: test
  script:
    # Step 1: Build all images from your root docker-compose.yml
    - docker-compose -f docker-compose.yml build

    # Step 2: Start all services (client, server, mongo) in the background
    - docker-compose -f docker-compose.yml up -d

    # Step 3: Run tests in the 'server' container
    - docker-compose -f docker-compose.yml exec -T server npm test

    # Step 4: Shut down and clean up
    - docker-compose -f docker-compose.yml down
