services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongotestData:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  flaskapiserver:
    build: 
      context: ./XGBoostModel
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  mongotestData:

networks:
  app-network:
